package com.example.mbcevjeostanyasproba

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

@Parcelize
data class Manga(
    val name: String,
    val ReleaseDate: Int,
    val Author: String,
    val Genre: String,
    val Plot: String,
    val ResId: Int,
) : Parcelable

fun createManga(): List<Manga> {
    return listOf(
        Manga(
            "Tokyo ghoul",
            2011,
            "Sui Ishida",
            "Horror, Dark fantasy, Action",
            "The story follows Ken Kaneki, a student who barely survives a deadly encounter with Rize Kamishiro, his date who reveals herself as a ghoul and tries to eat him. He is taken to the hospital in critical condition. After recovering, Kaneki discovers that he underwent a surgery that transformed him into a half-ghoul. This was accomplished because some of Rize's organs were transferred into his body, and now, like normal ghouls, he must consume human flesh to survive. Ghouls who run a coffee shop called \"Anteiku\" (あんていく) take him in and teach him to deal with his new life as a half-ghoul. Some of his daily struggles include fitting into the ghoul society, as well as keeping his identity hidden from his human companions, especially from his best friend, Hideyoshi Nagachika.\n" +
                    "\n" +
                    "The prequel series Tokyo Ghoul [Jack] follows the youths of Kishō Arima and Taishi Fura, two characters from the main series who become acquainted when they join forces to investigate the death of Taishi's friend at the hands of a ghoul, leading to Taishi eventually following Arima's path and joining the CCG (Commission of Counter Ghoul), the federal agency tasked into dealing with crimes related to ghouls as well.\n" +
                    "\n" +
                    "The sequel series Tokyo Ghoul:re follows an amnesiac Kaneki under the new identity of Haise Sasaki (the result of horrific brain damage sustained from Kishō Arima). He is the mentor of a special team of CCG investigators called \"Quinx Squad\" that underwent a similar procedure as his, allowing them to obtain the special abilities of Ghouls in order to fight them but still being able to live as normal humans.",
            R.drawable.kaneki
        ),

        Manga(
            "Homunculus",
            2003,
            "Hideo Yamamoto",
            "Psychological horror, Psychological thriller",
            "Trepanation is the procedure of drilling holes in a person's head, supposedly increasing the circulation of blood and helping to improve the pressure inside one's skull, bringing out a person's sixth sense and causing them to gain superhuman powers such as ESP, being able to see ghosts, and controlling objects remotely with one's mind. This is speculative fiction based on the concept of trepanation.\n" +
                    "\n" +
                    "Susumu Nakoshi is a 34-year-old homeless man living out of his car. For two weeks, he has declined his fellow homeless men's invitations to set up a tent with them, preferring to sleep in his car. However, one day, he is accosted by a strange-looking man searching for participants to subject themselves to trepanation. Nakoshi tells the man to leave, and discards the flier he'd placed on his windshield. However, when his car is towed, he agrees to let medical student Manabu Itoh drill a hole in his skull in exchange for 700,000 yen. Itoh claims to be interested in trepanation for the sake of science; he is interested in humans, fascinated with ESP and the sixth sense, and wants to disprove the existence of the occult. Itoh's father owns a lab facility, as his father is a rich hospital director. Itoh performs the trepanation surgery on Nakoshi and does a variety of ESP tests. When Nakoshi reveals that he sees distorted humans when using only the left side of his body, Itoh researches and discovers that Nakoshi can see homunculi.\n" +
                    "\n" +
                    "Itoh explains psychoanalytic theory to Nakoshi after the yakuza incident.",
            R.drawable.nakoshi
        ),

        Manga(
            "Blue lock",
            2018,
            "Muneyuki Kaneshiro",
            "Sports, Thriller",
            "In 2018, the Japanese national team finished 16th in the FIFA World Cup. As a result, the Japan Football Association hires the football enigma Ego Jinpachi. His master plan to lead Japan to stardom is Blue Lock, a training regimen designed to create the world's greatest egotist striker. Those who fail Blue Lock will never again be permitted to represent any Japanese team. Yoichi Isagi, an unknown high school football player who is conflicted about his playing style, decides to join the program in order to become the best egotistical striker in the world.",
            R.drawable.isagi
        ),
        Manga(
            "Tomodachi Game",
            2013,
            "Mikoto Yamaguchi, Yuki Sato",
            "Psychological thriller",
            "High school student Yuuichi Katagiri, who values friendship above all else, enjoys a fulfilling life with his close friends Shiho Sawaragi, Tenji Mikasa, Makoto Shibe, and Yutori Kokorogi. However, after a particular incident, they're dragged into a debt repayment game. The only way to beat the \"Tomodachi Game\" is to not doubt their friends. Bound together by solid friendships, the game should've been easy, but...",
            R.drawable.katagiri
        ),
        Manga(
            "Chainsaw Man",
            2018,
            "Tatsuki Fujimoto",
            "Action, Comedy horror, Dark fantasy",
            "Part 1 – Public Safety Arc" + "\n" + "\n" +
            "Denji is a young man trapped in poverty, working off his deceased father's debt to the yakuza by working as a Devil Hunter, aided by Pochita, his canine companion and Chainsaw Devil. Denji is betrayed by the yakuza, who kill him for a contract with the Zombie Devil. Pochita makes a contract with Denji, merging with him as a human-devil Hybrid, under the condition that Denji live out his dreams of living a basic life such as having bread with jam, or falling in love with a woman and being intimate with one. By pulling on a cord in his chest, Denji then becomes Chainsaw Man and massacres the yakuza. In the aftermath, he joins a team of governmental Devil Hunters, the Public Safety Division, led by Makima, who assigns him to kill the Gun Devil. Denji fights through multiple enemies who seek Chainsaw Man's power, and trains with his partner, Power the Blood Fiend, under the veteran Devil Hunter Kishibe.\n" +
                    "\n" +
                    "Makima later turns out to be the Control Devil, ultimately seeking to control Pochita, as he has the power to erase evil concepts from the world by consuming their Devils. Makima almost defeats the Gun Devil, until it retreats inside the dead body of Denji’s partner, Aki Hayakawa, forcing Denji to kill him in self-defense. Later, she kills Power in front of Denji, causing him to turn catatonic and turn his body over to Pochita.\n" +
                    "\n" +
                    "However, Kishibe organizes a raid to rescue Denji, and with his help as well as a frightened former teammate named Kobeni Higashiyama and a fragment of Power's blood, Denji kills Makima. Kishibe later reveals a reborn Control Devil, now a little girl named Nayuta. He asks Denji to look after her, and Pochita supports this mission in Denji's dreams. Denji begins attending high school while also fighting Devils as a vigilante." + "\n" + "\n" + "\n" +
            "Part 2 – School Arc" + "\n" + "\n" +
            "Asa Mitaka is an introverted high school student attending East High School, who has trouble finding her place in society following her mother's death to the Typhoon Devil. One day, after accidentally killing her class' pet Chicken Devil Bucky, she is confronted by the Class President who has made a contract with the Justice Devil. She attempts to kill Asa, but Yoru, the War Devil appears in the form of a bird and makes a contract with Asa, inhabiting her body and making her a living Fiend host, under the condition that she kills Chainsaw Man. After her quick vengeance, Asa seeks to find Chainsaw Man, though she and Yoru have differing goals: Asa wants Yoru to leave her body, while Yoru wants to reclaim the Nuclear Weapons Devil which was consumed by Pochita. They join the school's Devil Hunter Club, where they are partnered with Hirofumi Yoshida (a former coworker of Denji who is revealed to be attending Fourth East) and Yuko, an outgoing student who befriends her.\n" +
                    "\n" +
                    "Meanwhile, Denji has adapted to his new life as a normal high school student, also attending Fourth East, while using his newfound superhero fame to attract women. Hirofumi keeps tabs on him under an unknown mission. Knowing that Denji is still desperate for a girlfriend, Hirofumi introduces Denji to Asa, who he attempts to reveal to her that he is Chainsaw Man, but fails.\n" +
                    "\n" +
                    "Asa visits Yuko and later discovers that she also formed a contract with the Justice Devil and plans on enacting revenge on everyone who bullied Asa. Using Yoru's devil abilities, Asa confronts Yuko, but accidentally kills her. At that moment, a stranger walks up to her and revives Yuko for \"her little sister\", turning her into a giant devil rampaging through the school. Denji attacks Yuko, but she escapes. The now-disfigured Yuko bids farewell to Asa and goes on the run for help, but a mysterious impostor posing as Chainsaw Man kills her.\n" +
                    "\n" +
                    "Following the incident, Asa and Yoru bump into and meet Haruka Iseumi, the President of both the Devil Hunter's Club and the Student Council, who has taken interest in her and the stranger. Haruka tells Asa and Yoru that he is Chainsaw Man, showing them the dangling cord attached to his chest as proof. Believing him, Asa is then made by Yoru to go find someone she can kill and turn into a weapon. Spotting Denji to be the perfect target, she then goes on a date with him in order to kill him and turn him into a weapon. During the date, while she is alone, the stranger suddenly appears behind her and the stranger then reveals herself to be the Hunger/Famine Devil or \"Fami\", who then isolates her, bringing Yoru and herself outside and seemingly assists her in her quest to turn Denji into a weapon as the two, along with Hirofumi and Haruka, are trapped by the returning Eternity Devil in an aquarium. During this time period, Asa learns that Haruka is not the impostor, and is instead a big fan of Chainsaw Man. Asa kills the Eternity Devil, and Yoru attempts to turn Denji into a weapon. To Asa and Yoru's surprise, this fails.\n" +
                    "\n" +
                    "Later, Denji takes Asa to his house, where he explains the rules of the house set by Nayuta, including not to make out with him. Yoru immediately possesses Asa and makes out with Denji, causing an arriving Nayuta to use her Control Devil powers on her. This leaves Denji shocked as Nayuta tells Denji that she turned Yoru into a pet as she does not like Asa's \"scent\", thinking Yoru is trying to take Denji away from her, only agreeing to turn her back if Denji lets her have ice-cream everyday and he does not have intimate moments with Asa. Nayuta tells Denji she is going to erase Asa's and Yoru's memories leading from the date up to Nayuta using her powers on her, which he agrees with.\n" +
                    "\n" +
                    "Later, outside the high school, Yoru tells Asa that Denji might not be into her saying they might've been stood up. Asa takes this as a positive, as she is thankful he \"forgot\" but she goes to add she desires human touch as she was confined with Denji for too long but negates her affection for Denji on hormones and that her time would be better used in solitude, studying. She is then approached by Hirofumi as he asks her if she could keep him company. Both talk in the Devil Hunter club room and Asa notes that Hirofumi is similar to her, seemingly hinting that he likes her, but instead, Hirofumi asks her to stay away from Denji. Nayuta notices that there is a scent of a particularly nasty Devil nearby, and encourages Denji to investigate as Chainsaw Man. As a depressed Asa is walking back home, a dead body falls in front of her, as multiple residents of her apartment building come outside.\n" +
                    "\n" +
                    "Elsewhere, in a restaurant, Fami and Hirofumi discuss the mysterious \"Prophecy of Nostradamus\", which forewarns humanity's extinction on July 1999. Fami reveals that a Primal Fear devil (a devil that has existed since the beginning of time) has appeared 40 seconds ago. Meanwhile, Asa and Yoru are confronted by the Primal Fear, known as the Falling Devil, which Yoru runs away from claiming she cannot win the fight. It is revealed that on the day Asa's mother died, Asa saved a cat, and at the orphanage she was sent to, the caretaker tried to persuade Asa to give up the cat. When Asa refused, the caretaker threw the cat into the river out of spite. Yoru is able to save Asa from falling to her death, and Asa admits that her true fears are of solitude and companionship. As the Falling Devil collects human body parts to give to a mysterious worm-shaped Devil, Denji attacks it.",
            R.drawable.denji

        ),
        Manga(
            "Berserk",
            1989,
            "Kentaro Miura",
            "Dark fantasy, Epic fantasy, Sword and sorcery",
            "Guts is a lone warrior who was born from a hanged corpse and raised as a mercenary by his abusive adoptive father Gambino. It came to a head when Guts was forced to kill a drunk Gambino in self-defense, fleeing his mercenary group and becoming a wandering sellsword. His fearsome reputation catches the attention of Griffith, the charismatic leader of a mercenary group known as the Band of the Hawk. Griffith forces Guts to join the group after defeating him in battle, with Guts becoming his best fighter and main confidante. The Band is hired by the kingdom of Midland to help in its century-long war against the Chuder Empire. Guts learns of Griffith's desire to rule a kingdom of his own and his mysterious pendant known as a Behelit. The Behelit is instrumental when they are spared by Nosferatu Zodd, a monstrous immortal who leaves Guts with a cryptic warning of a painful demise for being Griffith's friend.\n" +
                    "\n" +
                    "As Griffith mingles with Midland nobility while acquainting himself with the king's daughter Charlotte, Guts begins developing feelings for his fellow commander Casca, the Hawks' only female member. Upon overhearing Griffith confessing to Charlotte that he only considers someone with their own dream as a friend, Guts decides to leave the group once Midland has won its war so he can find his own dream. Guts' decision inadvertently causes Griffith to fall into an emotional spiral that culminates in his arrest for seducing Charlotte in a moment of weakness. He loses his Behelit while subjected to endless torture, and the Hawks are declared criminals by the Midland army. Guts, having spent a year training to become a better swordsman, is warned by a mysterious being known as the \"Skull Knight\" that his actions have instigated an \"Eclipse\". Learning of the Hawks' predicament, Guts rejoins them to rescue Griffith, while also consummating his feelings for Casca.\n" +
                    "\n" +
                    "Despite a successful rescue while fleeing to Midland’s borders, the Hawks learn Griffith became physically incapable to lead them as they, Casca, and Guts determine how to proceed. When Griffith regains his Behelit while injuring himself during a solar eclipse, the pendant uses his blood to establish a temporary convergence of the physical world and the supernatural astral realm in the form of a hellscape. The Hawks encounter a quartet of archdemons known as the \"Godhand\" who have gathered for a ritual known as the Eclipse, revealing that Griffith has been chosen to become their final member and can only transcend his humanity if he offers his comrades as sacrificial offerings. Griffith accepts once reminded of the person he has always been. The Hawks are branded with demonic sigils, marking them for sacrifice and are subsequently slaughtered by the Godhand's Apostles—humans like Zodd who attained power by sacrificing their loved ones and humanity. Only Guts and Casca survive the massacre, but Griffith's first act as the being Femto is to rape Casca in front of Guts, with an enraged Guts losing his left forearm and right eye in his attempt to save her. They are rescued by the Skull Knight, but the ordeal traumatizes Casca enough to regress her mind to a childlike state. Guts learns from the Skull Knight that their \"Brands of Sacrifice\" makes them targets for specters and other beings of darkness on a nightly basis. Guts leaves Casca in the care of the blacksmith Godo, his adoptive daughter Erica, and Rickert, the last and youngest member of the Band of the Hawk, who survived by not being present at the Eclipse. Godo outfits Guts with a giant new sword, \"Dragonslayer\", and a prosthetic left arm with a built-in cannon and crossbow. Guts begins hunting down the Apostles to find and kill Griffith while followed by a demonic phantom called the Demon Child, which is actually Guts' and Casca's unborn child deformed by Femto's rape.\n" +
                    "\n" +
                    "Two years later, after having killed many Apostles and earning the nickname of \"the Black Swordsman\", Guts is joined by an elf named Puck. They are captured by Farnese, captain of the Holy See Church's Holy Iron Chain Knights, who believes Guts is a foretold harbinger of the apocalypse. Guts escapes after saving Farnese from specters, returning to an ailing Godo while learning that Casca wandered off. His search for her takes him to the refugee-infested city of St. Albion, a city the Godhand have prepared as the site for an Incarnation ceremony to give one of their own a physical form. Guts saves Casca from the fanatical Holy See bishop Mozgus as the city descends into nightmarish chaos from the souls of the dead attacking. Joined by Farnese, her bodyguard Serpico, and a young thief named Isidro, Guts and Casca survive the ordeal as a misshapen apostle living under St. Albion ingests the dying Demon Child and uses its body to reconstitute Griffith into a physical form.\n" +
                    "\n" +
                    "Guts encounters Griffith and Zodd at Godo's home and they engage in battle; the nearby enchanted mine, which sheltered Casca from the nightly demon attacks, is destroyed by Zodd while Griffith realizes some lingering traces of the Demon Child persist within him. To try and find a means of restoring her mind, Guts decides to journey with Casca to Puck's homeland of Elfhelm, on the island of Skellig. He allows Isidro, Farnese and Serpico to follow him out of fear that he will lose control of himself to his dark impulses—embodied as a demonic black dog within his mind—with Farnese becoming Casca's primary caretaker. At the same time, Griffith creates a second Band of the Hawk with Zodd and other Apostles to save Midland from the invading Kushan Empire, led by their rogue Apostle emperor, Ganishka.\n" +
                    "\n" +
                    "Guts' group encounters the witch Flora and her apprentice Schierke while saving a village from marauding trolls. Schierke begins to teach Farnese magic and dampens the effects of the sacrificial brands on Guts and Casca via magical seals. Flora gives Guts a dangerous relic known as the Berserker Armor, which increases his physical capability with the added risk of being consumed by his inner darkness. Flora is later killed when the New Band of the Hawk destroy the tree she made her home in. After escaping the destruction of Flora's home, during a full moon, Guts' party encounters Moonlight Boy, a small boy who does not speak but expresses a fondness for Guts and Casca. The boy disappears after the full moon passes. While Guts and his party secure a ship called the Seahorse, captained by Farnese's erstwhile fiancée, Prince Roderick, to reach Elfhelm amidst a Kushan attack on the port, Griffith's war with Ganishka reaches its climax; the emperor is destroyed following his transition into a god-like abomination that causes a worldwide overlapping of the mortal and astral realms. Unopposed and with Charlotte and the Holy See's blessing, Griffith establishes the city of Falconia to provide refuge for Midlanders and the rest of humanity from the numerous mythical creatures that manifested when the realms merged.\n" +
                    "\n" +
                    "After a dramatic battle with a supernatural island-sized monster known as the Sea God and recruiting a merrow girl named Isma, Guts' party reaches Elfhelm. The elf ruler, Danann, helps Farnese and Schierke travel into Casca's mind and restore her to her former self. Despite her recovery, Casca is still traumatized from her ordeal to the point of finding it difficult to be around Guts without remembering the events of the Eclipse. Farnese and Schierke begin training with the other apprentice witches and wizards living on Skellig, the former taking an interest in the power to heal human souls to help Casca. At the same time, the Skull Knight tells Guts his journey is at an end, introduces him to the creator of the Berserker Armor, and explains his own past with the Godhand and its leader Void. The Moonlight Boy appears on Elfheim during a full moon. Danann senses no malice from the child and he is allowed to stay, forming a mother-son bond with Casca. It is revealed that Moonlight Boy is the Demon Child, who can take control of the body Griffith resides in during a full moon. Griffith regains control of his host when day breaks and unnerves Guts with his inability to harm him before Zodd arrives. Griffith proceeds to abduct an incapacitated Casca while killing the island's giant spirit tree. The tree's destruction not only unleashes a torrent of evil spirits that nearly submerge the island, but also cause Danann, Isma and the other magical creatures, except Puck and Ivalera, to disappear into the Astral Realm. The survivors sail off on the Seahorse, defeated with their only advantage against Griffith gone. Guts breaks down in despair as a whirlpool begins to draw in the ship. Meanwhile, Griffith and Zodd return to the mainland with Casca.",
            R.drawable.gutsu
        ),
        Manga(
            "Kuroko's Basketball",
            2008,
            "Tadatoshi Fujimaki",
            "Comedy, Sports",
            "The Teiko Middle School basketball team dominated basketball teams within Japan, winning the middle school Nationals for three consecutive years. The star players of the team became known as the \"Generation of Miracles\". After graduating from middle school, the five star players went to different high schools with top basketball teams. However, there was a rumor that there was another player in the \"Generation of Miracles\": a phantom sixth man. This mysterious player is now a freshman at Seirin High, a new school with a powerful, if little-known, team. Now, Tetsuya Kuroko – the sixth member of the \"Generation of Miracles\", and Taiga Kagami – a naturally talented player who spent most of his youth in the US, aim to bring Seirin to the top of Japan by taking on Kuroko's former teammates one by one. The series chronicles Seirin's rise to become Japan's number one high school team. The Generation of Miracles include Ryota Kise, Shintaro Midorima, Daiki Aomine, Atsushi Murasakibara, and Seijuro Akashi.\n" +
                    "\n" +
                    "Seirin High team faced Ryota Kise's team first in a practice match. Although Kise was capable of copying all of Kagami's skills with added strength and speed, Kuroko's abilities helped narrow the distance and eventually, Seirin won this game. They then met Shintaro Midorima's school Shutoku in the preliminaries of Interhigh. The game was much more difficult; not only was Midorima considerably stronger than Kagami, but also Kuroko's ability of misdirection was completely shut down by Takao's Hawk Eyes. Seirin managed to defeat team Shutoku but their winning streak ended after they lost badly to Touhou Academy, whose basketball team included the Ace of the \"Generation of Miracles\" - Daiki Aomine. After this game, they lost their remaining two matches against Senshinkan and Meisei and were eliminated from the Interhigh. However, a new player arrives to join Seirin - Kiyoshi Teppei, the man who formed the Seirin Basketball team. They spent the entire summer training for the Winter Cup, even coincidentally meeting Shutoku while training.\n" +
                    "\n" +
                    "In the preliminaries, they met team Shutoku again. This match ended into a tie, so Seirin needed to defeat team Kirisaki Daichi in order to advance. Kirisaki Daichi's captain was Makoto Hanamiya, a member of the Uncrowned Kings well-known for his underhanded methods to win a match. However, they won and gained a ticket to the Winter Cup.",
            R.drawable.akashi
        ),
        Manga(
            "Naruto",
            1999,
            "Masashi Kishimoto",
            "Adventure, Fantasy comedy, Martial arts",
            "Part I" + "\n" + "\n" +
            "A powerful fox known as the Nine-Tails attacks Konoha, the hidden leaf village in the Land of Fire, one of the Five Great Shinobi Countries in the Ninja World. In response, the leader of Konoha and the Fourth Hokage, Minato Namikaze seals the fox inside the body of his newborn son, Naruto Uzumaki, making Naruto a host of the beast; this costs Naruto's father his life, and the Third Hokage returns from retirement to become the leader of Konoha again. Naruto is often scorned by Konoha's villagers for being the host of the Nine-Tails. Due to a decree by the Third Hokage forbidding any mention of these events, Naruto learns nothing about the Nine-Tails until 12 years later, when Mizuki, a renegade ninja, reveals the truth to Naruto. Naruto then defeats Mizuki in combat, earning the respect of his teacher, Iruka Umino.\n" +
                    "\n" +
                    "Shortly afterward, Naruto becomes a ninja and joins with Sasuke Uchiha, against whom he often competes, and Sakura Haruno, on whom he has a crush, to form Team 7, under an experienced sensei, the elite ninja Kakashi Hatake. Like all the ninja teams from every village, Team 7 completes missions requested by the villagers, ranging from doing chores and being bodyguards to performing assassinations.\n" +
                    "\n" +
                    "After several missions, including a major one in the Land of Waves, Kakashi allows Team 7 to take a ninja exam, enabling them to advance to a higher rank and take on more difficult missions, known as Chunin Exams. During the exams, Orochimaru, a wanted criminal, invades Konoha and kills the Third Hokage for revenge. Jiraiya, one of the three legendary ninjas, declines the title of Fifth Hokage and searches with Naruto for Tsunade whom he chooses to become Fifth Hokage instead.\n" +
                    "\n" +
                    "During the search, it is revealed that Orochimaru wishes to train Sasuke because of his powerful genetic heritage, the Sharingan. After Sasuke attempts and fails to kill his older brother Itachi, who had showed up in Konoha to kidnap Naruto, he joins Orochimaru, hoping to gain from him the strength needed to kill Itachi. The story takes a turn when Sasuke leaves the village: Tsunade sends a group of ninja, including Naruto, to retrieve Sasuke, but Naruto is unable to persuade or force him to come back. Naruto and Sakura do not give up on Sasuke; Naruto leaves Konoha to receive training from Jiraiya to prepare himself for the next time he encounters Sasuke, while Sakura becomes Tsunade's apprentice." + "\n" + "\n" + "\n" +
            "Part II" + "\n" + "\n" +
            "Two and a half years later, Naruto returns from his training with Jiraiya. The Akatsuki starts kidnapping the hosts of the powerful Tailed Beasts. Team 7 and other Leaf ninja fight against them and search for their teammate Sasuke. The Akatsuki succeeds in capturing and extracting seven of the Tailed Beasts, killing all the hosts except Gaara, who is now the Kazekage. Meanwhile, Sasuke betrays Orochimaru and faces Itachi to take revenge. After Itachi dies in battle, Sasuke learns from the Akatsuki founder Tobi that Itachi had been ordered by Konoha's superiors to destroy his clan to prevent a coup; he accepted, on the condition that Sasuke would be spared. Devastated by this revelation, Sasuke joins the Akatsuki to destroy Konoha in revenge. As Konoha ninjas defeat several Akatsuki members, the Akatsuki figurehead leader, Nagato, kills Jiraiya and devastates Konoha, but Naruto defeats and redeems him, earning the village's respect and admiration.\n" +
                    "\n" +
                    "With Nagato's death, Tobi, disguised as Madara Uchiha (one of Konoha's founding fathers), announces that he wants to capture all nine Tailed Beasts to cast an illusion powerful enough to control all humanity and achieve world peace. The leaders of the five ninja villages refuse to help him and instead join forces to confront his faction and allies. That decision results in a Fourth Shinobi World War between the combined armies of the Five Great Countries (known as the Allied Shinobi Forces) and Akatsuki's forces of zombie-like ninjas. The Five Kage try to keep Naruto, unaware of the war, in a secret island turtle near Kumogakure (Hidden Cloud Village), but Naruto finds out and escapes from the island with Killer Bee, the host of the Eight-Tails. At that time, Naruto—along with the help of Killer Bee—gains control of his Tailed Beast and the two of them head for the battlefield.\n" +
                    "\n" +
                    "During the conflict, it is revealed that Tobi is Obito Uchiha and not Madara as he claimed. Obito is a former teammate of Kakashi's who was thought to be dead. The real Madara saved Obito's life, and they have since collaborated. As Sasuke learns the history of Konoha, including the circumstances that led to his clan's downfall, he decides to protect the village and rejoins Naruto and Sakura to thwart Madara and Obito's plans. However, Madara's body ends up possessed by Kaguya Otsutsuki, an ancient princess who intends to subdue all humanity. A reformed Obito sacrifices himself to help Team 7 stop her. Once Kaguya is sealed, Madara dies as well. Sasuke takes advantage of the situation and takes control of all the Tailed Beasts, as he reveals his goal of ending the current village system. Naruto confronts Sasuke to dissuade him from his plan, and after they almost kill each other in a final battle, Sasuke admits defeat and reforms. After the war, Kakashi becomes the Sixth Hokage and pardons Sasuke for his crimes. Years later, Kakashi steps down while Naruto marries Hinata Hyuga and becomes the Seventh Hokage, raising the next generation.",
            R.drawable.obito
        )

    )

}